"""latitude & longitude to Float

Revision ID: df6450e1a4ad
Revises: b86df40a09ed
Create Date: 2024-10-19 06:22:20.762199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6450e1a4ad'
down_revision: Union[str, None] = 'b86df40a09ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'latitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               postgresql_using='latitude::float',
               existing_nullable=False)
    op.alter_column('logs', 'longitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               postgresql_using='longitude::float',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'longitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               postgresql_using='longitude::varchar',
               existing_nullable=False)
    op.alter_column('logs', 'latitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               postgresql_using='latitude::varchar',
               existing_nullable=False)
    # ### end Alembic commands ###
